---
- name: Installing Telnet
  hosts: dev
  tasks:
    - name: Installing Telnet
      yum:
        name: telnet
        state: present

    - name: Validating if Telnet is installed
      shell: rpm -qa telnet
      register: RPM_OUTPUT

    - debug:
        var: RPM_OUTPUT
