---
- name: Installing Telnet
  hosts: dev
  tasks:
    - name: removing Telnet
      yum:
        name: telnet
        state: absent

    - name: Validating if Telnet is installed
      shell: rpm -qa telnet
      register: RPM_OUTPUT

    - debug:
        var: RPM_OUTPUT

    - name: Installing net-tools pkg
      yum:
        name: net-tools
        state: present
